### PR TITLE
Fix msg-filename kept open after edition

### PR DESCRIPTION
**Pull request by Lorac**
--msg-filename type is now a Path and not a managed click.File.
This makes it easier to control the opening and closing of the file.

Context manager will make sure that the file we use will be refreshed after
edition.

Fixes: #180

### CODE REVIEW

**Comment by Lorac** [comment]
@jorisroovers I would like to add a test for this, but I think I'll need a pointer.

**Comment by jorisroovers** [comment]
Thanks for this fix. At first sight, it definitely looks good to me.

As you probably saw, tests failing is because of import-order issue (easy fix):

```bash
gitlint/cli.py:10:0: C0411: standard import "import pathlib" should be placed before "import click" (wrong-import-order)
```

I agree we probably do need a test specific for this scenario, to avoid regressions in the future. 

i.e. a test cases that: 

1. Installs git commit message hook
2. Uses a commit message with violations, checks that violations are as expected
3. Edits the commit message and fixes violations using the hook edit prompt
4. Checks that no violations are reported

Testing the hook end-to-end has always been a tricky though - the related test code might be a bit of a head scratcher initially.

Some pointers:

- Closest unit test, probably needs to be duplicated and modified: [https://github.com/jorisroovers/gitlint/blob/c175e45b8ce14af9e55c442a30c95ecc65fcee68/gitlint/tests/cli/test_cli_hooks.py#L125](https://github.com/jorisroovers/gitlint/blob/c175e45b8ce14af9e55c442a30c95ecc65fcee68/gitlint/tests/cli/test_cli_hooks.py#L125)
- Closest integration/system test. These invoke gitlint from the commandline, so no internal gitlint code is tested, only behavior. Same as unit test: would need to be duplicated and edited. [https://github.com/jorisroovers/gitlint/blob/c175e45b8ce14af9e55c442a30c95ecc65fcee68/qa/test_hooks.py#L110](https://github.com/jorisroovers/gitlint/blob/c175e45b8ce14af9e55c442a30c95ecc65fcee68/qa/test_hooks.py#L110)
- Either a unit or integration tests is fine, I don't think we need both

I'm happy to spend some time myself, please let me know, I should have time in the next few days.

Thanks!

**Comment by Lorac** [comment]
@jorisroovers Thanks for looking at it. I added a test. If you know a way to make it better I would like to know.

**Comment by jorisroovers** [comment]
Superceded by #491, closing this one.

**Pull request closed without merging**
