### PR TITLE
Run on windows

### PR DESCRIPTION
**Pull request by byrney**
This MR updates gitlint to run on windows. The unit tests also run on windows but the qa tests don't.

* Replace use of sh with a (very) cut-down version in gitlint/sh.py (gitlint + unit tests)
* Update gitlint and unit tests to run on windows

The amount of sh functionality used by gitlint is quite small and neatly encapsulated inside the _git method. Originally I thought I could drop in a replacement for _git but nearly all the tests mock out sh so that would have required modifying almost all of them. Replacing sh meant I could keep the unit tests largely unchanged to support the shift to windows.

The changes for windows are straight-forward, mostly in the unit tests, slashes need to be `path.join` and the encoding when reading sample files needs to be explicity specified (the commit has more details). 

The QA tests use much more of the sh functionality (particularly fake ttys) so I left those as is for now. Some are easy enough to adapt (see this wip commit for examples: https://github.com/byrney/gitlint/commit/50bc2c93757b08f63ade2329f9a7af8a3b48756e) but others require significant effort or may never be runnable on windows.

If there is appetite I can do another PR to make the majority of QA run on both platforms and mark the rest to skip on windows.

Caveats

* I didn't update the docs. They say "windows is not supported" which may continue to be true. 
* Gitlint does not work in mintty (the git bash windows terminal) unless run under `winpty` (due to the way it detects terminal vs pipe)
* Calling it `sh.py` may be confusing since `sh` is still used in qa. The alternative is a big search/replace on the tests to use a new name for `gitlint/sh.py`
* I tested on py2.7 and py3.6 I'm hoping travis will tell me if there are problems with other versions when this PR gets CI'd.
* We are running this fork in our linux and CI envs now and will start rolling out to windows desktops this week/next

Related Issues: #20

### CODE REVIEW

**Comment by jorisroovers** [comment]
Hi, 

this is awesome - thanks for doing this.

> The amount of sh functionality used by gitlint is quite small and neatly encapsulated inside the _git method

Yes! This was intentionally done a while back to make it easier for this change to be implemented at some point in the future - glad you found that :-)

I'm going to need some quality time to review and test this change myself. Given the foundational nature of this change, I'm inclined to be quite careful with accepting it without doing my own due diligence. I've been burnt before by the dozens of edge-cases that come with subprocess/shell execution (hence why I went to using ```sh``` originally).

In addition, I only tend to work on gitlint a couple of times a year, when I can make the time (this is a hobby project :-)). I promise I'll take a decent look at this at some point, but just a heads up that it might be a while (think months) before this actually get's merged and released.

Also, wrt Travis, I've see random integration test failures in the past - I'm fairly convinced this is a Travis issue because I've never had those issues outside of Travis and retriggering usually resolves these issues.

Thanks again for this PR!

**Comment by byrney** [comment]
It seems I had a bit more work to do to support all the python versions required. I've marked this as wip while I sort those out.  I'll change the title and drop a comment here when it's passing.

**Comment by byrney** [comment]
I think these are good now. You're right the travis tests don't seem to be 100% reliable. I had 2.7 failing and 3.6 passing. I changed a commit message and now 2.7 passed and 3.6 fails ( but works locally). I've tested 2.6, 2.7, 3.3 and 3.6 locally so fairly confident the travis failures are not real ones.

**Comment by byrney** [comment]
I just noticed that sh is still installed by setup.py. It will be skipped on windows so it's not doing any harm but it's no longer required to run gitlint (only for dev) so it could be removed.  Let me know if you prefer to remove it.

**Comment by wlgrd** [comment]
Any thoughts about moving forward with this?

**Comment by jorisroovers** [comment]
I just merged a branch to master that provides basic support for Windows. The relevant commits were heavily inspired by this PR, so really appreciate the work that was put in here. Thanks again!

In the end, I had to rewrite things slightly to align with some changes that had happened in the meantime and to incorporate some other tweaks.

In any case, I'll be pushing a new release with experimental windows support later in the week. Please use #20 or [any of the other relevant issues](https://github.com/jorisroovers/gitlint/issues?q=is%3Aissue+is%3Aopen+label%3Awindows) for follow-up, I'm closing out this PR.

**Pull request closed without merging**
